name: Build and Version Bump

permissions:
  contents: write

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      skip-build:
        description: "Skip build step"
        required: false
        default: "false"

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip-build]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: npm run build

      - name: Bump version and push tag
        if: success()
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          npm version patch -m "ci: bump version to %s [skip ci]"
          # Add the build output
          git add dist
          git commit -m "chore: add build output [skip ci]" || echo "No changes to commit"
          git push origin HEAD --tags
